language: node_js

node_js: "10"

cache: yarn

deploy:
  provider: script
  script: yarn deploy
  skip-cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
