language: node_js

node_js:
  - "10"

cache: yarn

script:
  - yarn build

deploy:
  provider: script
  script: GITHUB_TOKEN=$GITHUB_TOKEN yarn deploy
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
